/**
 * cookie manager - simple file-based cookie management for desktop app
 * no http api needed - uses file operations and electron dialogs
 */

const fs = require("fs").promises
const { readFileSync } = require("fs")
const path = require("path")
const { APP_CONFIG } = require("../utils/constants")
// the engine reads the same jar with the same parser - see utils/cookie-jar
const {
  inspectCookieContent,
  hasNetscapeHeader,
  isYouTubeDomain,
  readJar,
  JAR_DOMAIN_FLAG
} = require("../utils/cookie-jar")

/**
 * a cookie jar is credentials, so it is written the way a private key is:
 * owner only, on a directory nobody else can walk into. these were 0644 on an
 * 0755 directory, which on a shared machine is a readable youtube login.
 */
const JAR_MODE = 0o600
const JAR_DIR_MODE = 0o700

/**
 * cookie exports run to a few kilobytes; a megabyte is already absurd.
 *
 * the picker accepts any .txt, and the whole file is read into memory and
 * copied several times over to normalize it. without a bound, picking a video
 * by mistake hangs the main process rather than being told no.
 */
const MAX_JAR_BYTES = 1024 * 1024

/**
 * the header yt-dlp writes itself, copied so an imported jar is spelled the way
 * the thing that reads it spells one
 */
const NETSCAPE_HEADER =
  "# Netscape HTTP Cookie File\n# This file is generated by yt-dlp.  Do not edit.\n\n"

/**
 * put an imported jar into the shape yt-dlp writes
 *
 * two things, both taken from yt_dlp/cookies.py rather than invented here:
 *
 *   - line endings become \n, which is what its _really_save() emits. it reads
 *     with universal newlines so crlf would load too, but the FAQ blames
 *     mismatched endings for "HTTP Error 400" and emitting exactly what yt-dlp
 *     emits costs nothing. on windows python turns them back into crlf the
 *     first time yt-dlp saves the jar
 *   - the magic first line is added when it is missing. MozillaCookieJar reads
 *     it off line one and raises for the whole file without it, so a jar of
 *     perfectly good rows with no header is a jar that loads no cookies
 *
 * only newlines are stripped from the ends, never whitespace generally. A row
 * whose value is empty legitimately ends in a tab, and .trim() ate it on the
 * last line of the file: a seven column row became six and the cookie vanished
 * on import. The real binary keeps that row and writes it back with the tab
 * intact, so trimming it was ours alone.
 *
 * @param {string} raw - whatever the user handed us
 * @returns {string} a jar yt-dlp will load
 */
function normalizeJar(raw) {
  const content = String(raw)
    .replace(/\r\n?/g, "\n")
    .replace(/^\n+/, "")
    .replace(/\n+$/, "")

  return hasNetscapeHeader(content)
    ? `${content}\n`
    : `${NETSCAPE_HEADER}${content}\n`
}

/**
 * the wrong file, told apart the way yt-dlp tells it apart
 *
 * a json export is the common mistake - several extensions offer it - and
 * prepending a netscape header to json would produce a file that imports
 * "successfully" and holds nothing. yt-dlp checks the first character for
 * exactly this and says so; there is no reason to say it differently.
 */
function looksLikeJson(content) {
  const first = String(content).trim().charAt(0)

  return first === "[" || first === "{" || first === '"'
}

// written by older builds; it claimed the cookies worked when all it knew was
// that the file existed, so it is stripped wherever status is read or written
const LEGACY_STATUS_KEYS = ["working"]

function withoutLegacyKeys(status) {
  const cleaned = { ...status }

  for (const key of LEGACY_STATUS_KEYS) {
    delete cleaned[key]
  }

  return cleaned
}

class CookieManager {
  constructor() {
    this.cookieDir = APP_CONFIG.COOKIES_DIR
    this.cookieFile = path.join(this.cookieDir, "youtube_cookies.txt")
    this.statusFile = path.join(this.cookieDir, "cookie_status.json")
    this.isValid = false
    this.lastTest = null

    this.initialize()
  }

  /**
   * initialize cookie manager
   */
  async initialize() {
    try {
      // create cookie directory if it doesn't exist
      await fs.mkdir(this.cookieDir, { recursive: true, mode: JAR_DIR_MODE })
      // recursive mkdir leaves an existing directory's mode alone, and older
      // builds made this one 0755 - so tighten it every start rather than only
      // on the install that happens to create it
      await fs.chmod(this.cookieDir, JAR_DIR_MODE).catch(() => {})

      // create empty cookie file if it doesn't exist
      await this.ensureCookieFile()

      // check if cookies are valid
      this.isValid = await this.validateCookieFile()

    } catch (error) {
      console.error("cookie manager initialization failed:", error)
    }
  }

  /**
   * ensure cookie file exists with proper format
   */
  async ensureCookieFile() {
    try {
      await fs.access(this.cookieFile)
      // an existing jar from an older build is still 0644
      await fs.chmod(this.cookieFile, JAR_MODE).catch(() => {})
    } catch (error) {
      // file doesn't exist, create empty one
      await this.createEmptyCookieFile()
    }
  }

  /**
   * create empty cookie file with proper netscape format
   *
   * throws rather than logging: this is how clearCookies() removes a login, and
   * swallowing the failure let it report the credentials gone while they were
   * still on disk.
   */
  async createEmptyCookieFile() {
    await this.writeJar(NETSCAPE_HEADER)
  }

  /**
   * replace the jar without ever leaving a half-written one behind
   *
   * a plain writeFile opens with O_TRUNC, so a failure part way through - a
   * full disk, the process dying - destroys the old jar and leaves a truncated
   * file in its place. Writing beside it and renaming makes the swap atomic:
   * either the new jar is there or the old one still is.
   */
  async writeJar(content) {
    const temp = `${this.cookieFile}.${process.pid}.tmp`

    try {
      await fs.writeFile(temp, content, { encoding: "utf8", mode: JAR_MODE })
      await fs.rename(temp, this.cookieFile)
    } catch (error) {
      await fs.unlink(temp).catch(() => {})
      throw error
    }
  }

  /**
   * describe what the cookie jar actually holds
   *
   * "has some non-comment lines" was too weak: an expired jar, or one exported
   * for an unrelated site, would still be treated as a working youtube login.
   *
   * @returns {Promise<Object>} {total, youtube, expired, hasSid, signedIn, usable}
   */
  async inspectCookieFile(now = Date.now()) {
    try {
      const content = await fs.readFile(this.cookieFile, "utf8")

      return inspectCookieContent(content, now)
    } catch (error) {
      console.error("failed to read cookie file:", error.message)
      return {
        total: 0,
        youtube: 0,
        expired: 0,
        hasSid: false,
        signedIn: false,
        usable: false,
        loadError: null
      }
    }
  }

  /**
   * check if cookie file has usable youtube cookies
   * @returns {Promise<boolean>} true if a live youtube cookie is present
   */
  async validateCookieFile() {
    const { usable } = await this.inspectCookieFile()

    return usable
  }

  /**
   * import cookies from content string
   * @param {string} cookieContent - cookie file content
   * @returns {Promise<boolean>} success status
   */
  async importCookies(cookieContent) {
    if (!cookieContent || !cookieContent.trim()) {
      throw new Error("that file is empty.")
    }

    // into yt-dlp's own shape: its line endings, and its magic first line
    const content = normalizeJar(cookieContent)

    /**
     * everything that disqualifies a file, checked before anything is written.
     *
     * picking the wrong .txt used to overwrite the jar with it and then answer
     * "No cookies imported" - the same words an untouched install shows - so a
     * mistake that destroyed a working login was indistinguishable from one
     * that did nothing. Nothing below replaces the file it is refusing.
     *
     * the bar is "is this a youtube cookie jar", not "is this a login": a jar
     * of signed-out youtube cookies is a real jar, imports, and says what it
     * is. A jar for some other site is not - it cannot help a youtube download
     * and accepting it costs the user the login they already had.
     */
    const { error, cookies } = readJar(content)

    if (error === JAR_DOMAIN_FLAG) {
      throw new Error(
        "that cookie file is malformed. a domain column disagrees with its own subdomain flag, so yt-dlp refuses the whole thing. export a fresh one instead of editing it by hand."
      )
    }

    if (cookies.length === 0) {
      throw new Error(
        "there are no cookies in that file. export cookies.txt with the extension, then pick that one."
      )
    }

    if (!cookies.some((cookie) => isYouTubeDomain(cookie.domain))) {
      throw new Error(
        "that file has cookies, but none of them are youtube's. export cookies.txt while you're on youtube.com."
      )
    }

    // a failure past this point is real - a full disk, a permission problem -
    // and used to be swallowed into "imported: false", which the ui showed as
    // a successful import that merely wasn't a login. it throws now, so the
    // user is told what actually happened
    await this.writeJar(content)

    this.isValid = await this.validateCookieFile()

    await this.updateStatus({
      lastImport: new Date().toISOString(),
      valid: this.isValid,
      size: content.length
    })

    return this.isValid
  }

  /**
   * import cookies from file path
   * @param {string} filePath - path to cookie file
   * @returns {Promise<boolean>} success status
   */
  async importCookieFile(filePath) {
    try {
      // the picker accepts any .txt, so the size is checked before the file is
      // pulled into memory rather than after
      const { size } = await fs.stat(filePath)

      if (size > MAX_JAR_BYTES) {
        throw new Error(
          "that file is way too big to be a cookie export. pick the cookies.txt the extension saved."
        )
      }

      // read the cookie file
      const content = await fs.readFile(filePath, "utf8")

      /**
       * the one thing worth refusing outright.
       *
       * this used to demand "# Netscape HTTP Cookie File" appear somewhere in
       * the file, which was wrong twice over: yt-dlp accepts the shorter
       * "# HTTP Cookie File" too, and it wants the magic on line one rather
       * than anywhere at all. So a valid export was turned away while a file
       * mentioning the header in a comment sailed through.
       *
       * a missing header is now repaired by importCookies() like any other
       * pasted jar. json is the exception: it is the common wrong file, and
       * giving it a header would produce an import that "succeeds" with no
       * cookies in it. yt-dlp reads the first character to tell json apart and
       * says exactly this, so we say the same thing.
       */
      if (looksLikeJson(content)) {
        throw new Error(
          "that's json, not a netscape cookies.txt. export it as cookies.txt instead."
        )
      }

      // import the content
      return await this.importCookies(content)
    } catch (error) {
      console.error("failed to import cookie file:", error.message)
      throw error
    }
  }

  /**
   * re-read the jar and recompute isValid, synchronously
   *
   * isValid used to be computed once at startup and then trusted: a jar
   * replaced by hand, or one whose cookies expired while the app stayed open,
   * kept its old verdict until something happened to call refresh(). downloads
   * then either skipped a perfectly good jar or passed a dead one. nothing is
   * cached here on purpose - a cookie jar is a few kilobytes, the engine
   * already re-reads it per operation, and both staleness modes need a fresh
   * read anyway (expiry is a function of the clock, not of the file).
   *
   * @returns {Object} the inspection, whatever the file turned out to be
   */
  inspectNow() {
    try {
      return inspectCookieContent(readFileSync(this.cookieFile, "utf8"))
    } catch {
      // missing or unreadable file - the same answer either way
      return {
        total: 0,
        youtube: 0,
        expired: 0,
        hasSid: false,
        signedIn: false,
        usable: false,
        loadError: null
      }
    }
  }

  revalidate() {
    this.isValid = this.inspectNow().usable

    return this.isValid
  }

  /**
   * get cookie file path for yt-dlp
   *
   * deliberately a lower bar than hasValidCookies(). Gating this on our own
   * authentication test meant a jar yt-dlp would happily load and send - a
   * partial export, a session mid-rotation - was silently withheld from the
   * download, which is a decision that belongs to yt-dlp rather than to us.
   * What we do withhold is a jar it cannot load at all, because --cookies on
   * one of those aborts the run instead of downloading without them.
   *
   * @returns {string|null} path to cookie file, or null if there is no point
   */
  getCookieFilePath() {
    const { loadError, youtube } = this.inspectNow()

    return !loadError && youtube > 0 ? this.cookieFile : null
  }

  /**
   * is the user signed in, as yt-dlp would judge it?
   *
   * this is the question the ui asks, and it is narrower than the one above:
   * cookies that authenticate, not cookies worth sending.
   *
   * @returns {boolean} true if cookies are valid
   */
  hasValidCookies() {
    return this.revalidate()
  }

  /**
   * does the jar hold youtube cookies at all, signed in or not?
   *
   * what analytics means by has_youtube_cookies, which is not the same as
   * "is a login" and was reporting the narrower number.
   *
   * @returns {boolean}
   */
  hasYouTubeCookies() {
    return this.inspectNow().youtube > 0
  }

  // testCookies() used to live here. It reported working: this.isValid with the
  // note "handled by Python server" - the file simply existing was presented as
  // proof the cookies worked. Nothing called it, and the ipc cookie test now
  // owns this, so the claim is gone rather than left to be found and reused.

  /**
   * get cookie status information
   * @returns {Promise<Object>} cookie status
   */
  async getStatus() {
    // the jar may have been replaced or expired since anyone last looked
    this.revalidate()

    try {
      // try to read existing status
      const statusContent = await fs.readFile(this.statusFile, "utf8")
      // a status file written by an older build still carries "working"
      const status = withoutLegacyKeys(JSON.parse(statusContent))

      // add current file info
      const stats = await fs.stat(this.cookieFile)
      status.fileSize = stats.size
      status.fileModified = stats.mtime.toISOString()
      status.valid = this.isValid
      status.cookiesLoaded = this.isValid

      return status
    } catch (error) {
      // return default status if file doesn't exist or is invalid
      return {
        valid: this.isValid,
        cookiesLoaded: this.isValid,
        lastImport: null,
        lastTest: this.lastTest,
        fileSize: 0,
        fileModified: null
      }
    }
  }

  /**
   * update cookie status
   * @param {Object} updates - status updates
   */
  async updateStatus(updates) {
    try {
      const currentStatus = await this.getStatus()
      // strip here too, so a caller cannot write the retired key back in
      const newStatus = withoutLegacyKeys({ ...currentStatus, ...updates })

      await fs.writeFile(
        this.statusFile,
        JSON.stringify(newStatus, null, 2),
        "utf8"
      )
    } catch (error) {
      console.error("failed to update cookie status:", error)
    }
  }

  /**
   * clear cookies (reset to empty file)
   * @returns {Promise<boolean>} success status
   */
  async clearCookies() {
    // no catch: this is the one operation whose failure the user must not be
    // told went through. it used to report the credentials removed whether or
    // not the write landed, so a jar that could not be overwritten stayed on
    // disk behind a ui that said it was gone
    await this.createEmptyCookieFile()
    this.isValid = false

    await this.updateStatus({
      lastClear: new Date().toISOString(),
      valid: false,
      cookiesLoaded: false,
      extractionCheck: "skipped",
      note: "nothing imported yet"
    })

    return true
  }

  /**
   * get cookie file size and basic info
   * @returns {Promise<Object>} cookie file info
   */
  async getFileInfo() {
    try {
      const stats = await fs.stat(this.cookieFile)
      const inspection = await this.inspectCookieFile()

      // the inspection just answered the question - keep the field in step
      this.isValid = inspection.usable

      return {
        exists: true,
        size: stats.size,
        modified: stats.mtime.toISOString(),
        cookieCount: inspection.total,
        youtubeCookieCount: inspection.youtube,
        expiredCookieCount: inspection.expired,
        // carried through so the ui can tell "you were never signed in" from
        // "youtube signed you out", which read the same to a user and ask for
        // different things
        hasSid: inspection.hasSid,
        signedIn: inspection.signedIn,
        // a jar yt-dlp refuses whole reads as an empty one otherwise, and
        // "no cookies imported" is the wrong thing to say about a file that is
        // sitting right there full of them
        loadError: inspection.loadError ?? null,
        valid: this.isValid,
        path: this.cookieFile
      }
    } catch (error) {
      return {
        exists: false,
        size: 0,
        modified: null,
        cookieCount: 0,
        hasSid: false,
        signedIn: false,
        loadError: null,
        valid: false,
        path: this.cookieFile,
        error: error.message
      }
    }
  }
}

module.exports = CookieManager
